# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../_ui/sheet_creator_master.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_master(object):
    def setupUi(self, master):
        master.setObjectName("master")
        master.resize(640, 600)
        master.setMinimumSize(QtCore.QSize(640, 600))
        master.setMaximumSize(QtCore.QSize(640, 600))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        master.setFont(font)
        self.frame_base_settings = QtWidgets.QFrame(master)
        self.frame_base_settings.setGeometry(QtCore.QRect(20, 20, 290, 450))
        self.frame_base_settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_base_settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_base_settings.setObjectName("frame_base_settings")
        self.groupbox_ref_word = QtWidgets.QGroupBox(self.frame_base_settings)
        self.groupbox_ref_word.setGeometry(QtCore.QRect(10, 10, 270, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupbox_ref_word.setFont(font)
        self.groupbox_ref_word.setObjectName("groupbox_ref_word")
        self.lineedit_ref_word = QtWidgets.QLineEdit(self.groupbox_ref_word)
        self.lineedit_ref_word.setGeometry(QtCore.QRect(0, 20, 270, 40))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        self.lineedit_ref_word.setFont(font)
        self.lineedit_ref_word.setObjectName("lineedit_ref_word")
        self.groupbox_font_choice = QtWidgets.QGroupBox(self.frame_base_settings)
        self.groupbox_font_choice.setGeometry(QtCore.QRect(10, 80, 130, 100))
        self.groupbox_font_choice.setObjectName("groupbox_font_choice")
        self.checkbox_capital = QtWidgets.QCheckBox(self.groupbox_font_choice)
        self.checkbox_capital.setGeometry(QtCore.QRect(10, 30, 110, 20))
        self.checkbox_capital.setObjectName("checkbox_capital")
        self.checkbox_script = QtWidgets.QCheckBox(self.groupbox_font_choice)
        self.checkbox_script.setGeometry(QtCore.QRect(10, 50, 110, 20))
        self.checkbox_script.setChecked(True)
        self.checkbox_script.setObjectName("checkbox_script")
        self.checkbox_cursive = QtWidgets.QCheckBox(self.groupbox_font_choice)
        self.checkbox_cursive.setGeometry(QtCore.QRect(10, 70, 110, 20))
        self.checkbox_cursive.setObjectName("checkbox_cursive")
        self.groupbox_lines = QtWidgets.QGroupBox(self.frame_base_settings)
        self.groupbox_lines.setGeometry(QtCore.QRect(150, 80, 130, 100))
        self.groupbox_lines.setObjectName("groupbox_lines")
        self.spinbox_lines = QtWidgets.QSpinBox(self.groupbox_lines)
        self.spinbox_lines.setGeometry(QtCore.QRect(20, 40, 90, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spinbox_lines.setFont(font)
        self.spinbox_lines.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinbox_lines.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.spinbox_lines.setMinimum(1)
        self.spinbox_lines.setMaximum(30)
        self.spinbox_lines.setProperty("value", 5)
        self.spinbox_lines.setObjectName("spinbox_lines")
        self.groupbox_ref_word_settings = QtWidgets.QGroupBox(self.frame_base_settings)
        self.groupbox_ref_word_settings.setGeometry(QtCore.QRect(10, 190, 270, 120))
        self.groupbox_ref_word_settings.setObjectName("groupbox_ref_word_settings")
        self.label_rws_number = QtWidgets.QLabel(self.groupbox_ref_word_settings)
        self.label_rws_number.setGeometry(QtCore.QRect(10, 30, 190, 30))
        self.label_rws_number.setObjectName("label_rws_number")
        self.label_rws_prob = QtWidgets.QLabel(self.groupbox_ref_word_settings)
        self.label_rws_prob.setGeometry(QtCore.QRect(10, 80, 190, 30))
        self.label_rws_prob.setObjectName("label_rws_prob")
        self.spinbox_rws_number = QtWidgets.QSpinBox(self.groupbox_ref_word_settings)
        self.spinbox_rws_number.setGeometry(QtCore.QRect(210, 30, 50, 30))
        self.spinbox_rws_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinbox_rws_number.setMinimum(1)
        self.spinbox_rws_number.setMaximum(5)
        self.spinbox_rws_number.setObjectName("spinbox_rws_number")
        self.spinbox_rws_prob = QtWidgets.QDoubleSpinBox(self.groupbox_ref_word_settings)
        self.spinbox_rws_prob.setGeometry(QtCore.QRect(210, 80, 50, 30))
        self.spinbox_rws_prob.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinbox_rws_prob.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinbox_rws_prob.setDecimals(1)
        self.spinbox_rws_prob.setProperty("value", 80.0)
        self.spinbox_rws_prob.setObjectName("spinbox_rws_prob")
        self.groupbox_other_words_settings = QtWidgets.QGroupBox(self.frame_base_settings)
        self.groupbox_other_words_settings.setGeometry(QtCore.QRect(10, 320, 270, 120))
        self.groupbox_other_words_settings.setObjectName("groupbox_other_words_settings")
        self.label_ows_info = QtWidgets.QLabel(self.groupbox_other_words_settings)
        self.label_ows_info.setGeometry(QtCore.QRect(10, 30, 250, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ows_info.setFont(font)
        self.label_ows_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ows_info.setObjectName("label_ows_info")
        self.label_ows_very_close = QtWidgets.QLabel(self.groupbox_other_words_settings)
        self.label_ows_very_close.setGeometry(QtCore.QRect(10, 50, 190, 20))
        self.label_ows_very_close.setObjectName("label_ows_very_close")
        self.label_ows_close = QtWidgets.QLabel(self.groupbox_other_words_settings)
        self.label_ows_close.setGeometry(QtCore.QRect(10, 70, 190, 20))
        self.label_ows_close.setObjectName("label_ows_close")
        self.label_ows_other = QtWidgets.QLabel(self.groupbox_other_words_settings)
        self.label_ows_other.setGeometry(QtCore.QRect(10, 90, 190, 20))
        self.label_ows_other.setObjectName("label_ows_other")
        self.spinbox_ows_close = QtWidgets.QDoubleSpinBox(self.groupbox_other_words_settings)
        self.spinbox_ows_close.setGeometry(QtCore.QRect(210, 70, 50, 20))
        self.spinbox_ows_close.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinbox_ows_close.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinbox_ows_close.setDecimals(1)
        self.spinbox_ows_close.setMaximum(100.0)
        self.spinbox_ows_close.setProperty("value", 40.0)
        self.spinbox_ows_close.setObjectName("spinbox_ows_close")
        self.spinbox_ows_very_close = QtWidgets.QDoubleSpinBox(self.groupbox_other_words_settings)
        self.spinbox_ows_very_close.setGeometry(QtCore.QRect(210, 50, 50, 20))
        self.spinbox_ows_very_close.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinbox_ows_very_close.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinbox_ows_very_close.setDecimals(1)
        self.spinbox_ows_very_close.setProperty("value", 40.0)
        self.spinbox_ows_very_close.setObjectName("spinbox_ows_very_close")
        self.spinbox_ows_other = QtWidgets.QDoubleSpinBox(self.groupbox_other_words_settings)
        self.spinbox_ows_other.setGeometry(QtCore.QRect(210, 90, 50, 20))
        self.spinbox_ows_other.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinbox_ows_other.setReadOnly(True)
        self.spinbox_ows_other.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinbox_ows_other.setDecimals(1)
        self.spinbox_ows_other.setMaximum(100.0)
        self.spinbox_ows_other.setProperty("value", 40.0)
        self.spinbox_ows_other.setObjectName("spinbox_ows_other")
        self.frame_advanced_settings = QtWidgets.QFrame(master)
        self.frame_advanced_settings.setGeometry(QtCore.QRect(330, 20, 290, 450))
        self.frame_advanced_settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_advanced_settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_advanced_settings.setObjectName("frame_advanced_settings")
        self.checkbox_advanced_settings = QtWidgets.QCheckBox(self.frame_advanced_settings)
        self.checkbox_advanced_settings.setGeometry(QtCore.QRect(10, 10, 270, 20))
        self.checkbox_advanced_settings.setChecked(True)
        self.checkbox_advanced_settings.setObjectName("checkbox_advanced_settings")
        self.frame_enabled_advanced_settings = QtWidgets.QFrame(self.frame_advanced_settings)
        self.frame_enabled_advanced_settings.setEnabled(True)
        self.frame_enabled_advanced_settings.setGeometry(QtCore.QRect(0, 40, 290, 410))
        self.frame_enabled_advanced_settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_enabled_advanced_settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_enabled_advanced_settings.setObjectName("frame_enabled_advanced_settings")
        self.groupbox_very_close = QtWidgets.QGroupBox(self.frame_enabled_advanced_settings)
        self.groupbox_very_close.setGeometry(QtCore.QRect(10, 10, 270, 140))
        self.groupbox_very_close.setObjectName("groupbox_very_close")
        self.checkbox_vc_startend3 = QtWidgets.QCheckBox(self.groupbox_very_close)
        self.checkbox_vc_startend3.setGeometry(QtCore.QRect(10, 30, 250, 20))
        self.checkbox_vc_startend3.setObjectName("checkbox_vc_startend3")
        self.checkbox_vc_startend2 = QtWidgets.QCheckBox(self.groupbox_very_close)
        self.checkbox_vc_startend2.setGeometry(QtCore.QRect(10, 50, 250, 20))
        self.checkbox_vc_startend2.setObjectName("checkbox_vc_startend2")
        self.checkbox_vc_following4 = QtWidgets.QCheckBox(self.groupbox_very_close)
        self.checkbox_vc_following4.setGeometry(QtCore.QRect(10, 70, 250, 20))
        self.checkbox_vc_following4.setObjectName("checkbox_vc_following4")
        self.checkbox_vc_following3 = QtWidgets.QCheckBox(self.groupbox_very_close)
        self.checkbox_vc_following3.setGeometry(QtCore.QRect(10, 90, 250, 20))
        self.checkbox_vc_following3.setChecked(True)
        self.checkbox_vc_following3.setObjectName("checkbox_vc_following3")
        self.checkbox_vc_indep3 = QtWidgets.QCheckBox(self.groupbox_very_close)
        self.checkbox_vc_indep3.setGeometry(QtCore.QRect(10, 110, 250, 20))
        self.checkbox_vc_indep3.setObjectName("checkbox_vc_indep3")
        self.groupbox_word_list = QtWidgets.QGroupBox(self.frame_enabled_advanced_settings)
        self.groupbox_word_list.setGeometry(QtCore.QRect(10, 330, 270, 70))
        self.groupbox_word_list.setObjectName("groupbox_word_list")
        self.lineedit_word_list = QtWidgets.QLineEdit(self.groupbox_word_list)
        self.lineedit_word_list.setGeometry(QtCore.QRect(10, 30, 220, 30))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.lineedit_word_list.setFont(font)
        self.lineedit_word_list.setObjectName("lineedit_word_list")
        self.radiobutton_word_list_ok = QtWidgets.QRadioButton(self.groupbox_word_list)
        self.radiobutton_word_list_ok.setEnabled(False)
        self.radiobutton_word_list_ok.setGeometry(QtCore.QRect(240, 30, 20, 30))
        self.radiobutton_word_list_ok.setText("")
        self.radiobutton_word_list_ok.setCheckable(True)
        self.radiobutton_word_list_ok.setChecked(False)
        self.radiobutton_word_list_ok.setObjectName("radiobutton_word_list_ok")
        self.groupbox_close = QtWidgets.QGroupBox(self.frame_enabled_advanced_settings)
        self.groupbox_close.setGeometry(QtCore.QRect(10, 170, 270, 140))
        self.groupbox_close.setObjectName("groupbox_close")
        self.checkbox_c_startend2 = QtWidgets.QCheckBox(self.groupbox_close)
        self.checkbox_c_startend2.setGeometry(QtCore.QRect(10, 30, 250, 20))
        self.checkbox_c_startend2.setObjectName("checkbox_c_startend2")
        self.checkbox_c_following3 = QtWidgets.QCheckBox(self.groupbox_close)
        self.checkbox_c_following3.setGeometry(QtCore.QRect(10, 50, 250, 20))
        self.checkbox_c_following3.setObjectName("checkbox_c_following3")
        self.checkbox_c_following2 = QtWidgets.QCheckBox(self.groupbox_close)
        self.checkbox_c_following2.setGeometry(QtCore.QRect(10, 70, 250, 20))
        self.checkbox_c_following2.setChecked(True)
        self.checkbox_c_following2.setObjectName("checkbox_c_following2")
        self.checkbox_c_indep3 = QtWidgets.QCheckBox(self.groupbox_close)
        self.checkbox_c_indep3.setGeometry(QtCore.QRect(10, 90, 250, 20))
        self.checkbox_c_indep3.setObjectName("checkbox_c_indep3")
        self.checkbox_c_indep2 = QtWidgets.QCheckBox(self.groupbox_close)
        self.checkbox_c_indep2.setGeometry(QtCore.QRect(10, 110, 250, 20))
        self.checkbox_c_indep2.setObjectName("checkbox_c_indep2")
        self.frame_commands = QtWidgets.QFrame(master)
        self.frame_commands.setGeometry(QtCore.QRect(20, 490, 290, 90))
        self.frame_commands.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_commands.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_commands.setObjectName("frame_commands")
        self.pushbutton_generate = QtWidgets.QPushButton(self.frame_commands)
        self.pushbutton_generate.setGeometry(QtCore.QRect(10, 10, 130, 30))
        self.pushbutton_generate.setObjectName("pushbutton_generate")
        self.pushbutton_default_settings = QtWidgets.QPushButton(self.frame_commands)
        self.pushbutton_default_settings.setGeometry(QtCore.QRect(150, 10, 130, 30))
        self.pushbutton_default_settings.setObjectName("pushbutton_default_settings")
        self.pushbutton_help = QtWidgets.QPushButton(self.frame_commands)
        self.pushbutton_help.setGeometry(QtCore.QRect(10, 50, 130, 30))
        self.pushbutton_help.setObjectName("pushbutton_help")
        self.pushbutton_quit = QtWidgets.QPushButton(self.frame_commands)
        self.pushbutton_quit.setGeometry(QtCore.QRect(150, 50, 130, 30))
        self.pushbutton_quit.setObjectName("pushbutton_quit")
        self.frame_info = QtWidgets.QFrame(master)
        self.frame_info.setGeometry(QtCore.QRect(330, 490, 290, 90))
        self.frame_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info.setObjectName("frame_info")
        self.groupbox_state_info = QtWidgets.QGroupBox(self.frame_info)
        self.groupbox_state_info.setGeometry(QtCore.QRect(10, 10, 270, 70))
        self.groupbox_state_info.setObjectName("groupbox_state_info")
        self.textbrowser_state_info = QtWidgets.QTextBrowser(self.groupbox_state_info)
        self.textbrowser_state_info.setGeometry(QtCore.QRect(0, 20, 270, 50))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(8)
        self.textbrowser_state_info.setFont(font)
        self.textbrowser_state_info.setAcceptRichText(True)
        self.textbrowser_state_info.setObjectName("textbrowser_state_info")

        self.retranslateUi(master)
        QtCore.QMetaObject.connectSlotsByName(master)

    def retranslateUi(self, master):
        _translate = QtCore.QCoreApplication.translate
        master.setWindowTitle(_translate("master", "Sheet Creator X"))
        self.groupbox_ref_word.setTitle(_translate("master", "Mot de référence :"))
        self.groupbox_font_choice.setTitle(_translate("master", "Choix de polices :"))
        self.checkbox_capital.setText(_translate("master", "Capitale"))
        self.checkbox_script.setText(_translate("master", "Script"))
        self.checkbox_cursive.setText(_translate("master", "Cursive"))
        self.groupbox_lines.setTitle(_translate("master", "Lignes par police :"))
        self.groupbox_ref_word_settings.setTitle(_translate("master", "Génération du mot de référence :"))
        self.label_rws_number.setText(_translate("master", "Nombre max. de mots de\n"
"référence par ligne (1-5)"))
        self.label_rws_prob.setText(_translate("master", "Proba. d\'apparition du mot\n"
"de référence sur la ligne (%)"))
        self.groupbox_other_words_settings.setTitle(_translate("master", "Génération du reste de la grille :"))
        self.label_ows_info.setText(_translate("master", "Très proches + Proches + Divers = 100 %"))
        self.label_ows_very_close.setText(_translate("master", "Mots très proches (%)"))
        self.label_ows_close.setText(_translate("master", "Mots proches (%)"))
        self.label_ows_other.setText(_translate("master", "Mots divers (%)"))
        self.checkbox_advanced_settings.setText(_translate("master", "Réglages avancés"))
        self.groupbox_very_close.setTitle(_translate("master", "Définition de mot très proche  :"))
        self.checkbox_vc_startend3.setText(_translate("master", "Début ou fin sur 3 lettres"))
        self.checkbox_vc_startend2.setText(_translate("master", "Début ou fin sur 2 lettres"))
        self.checkbox_vc_following4.setText(_translate("master", "1 x 4 Lettres successives"))
        self.checkbox_vc_following3.setText(_translate("master", "1 x 3 Lettres successives"))
        self.checkbox_vc_indep3.setText(_translate("master", "3 x 1 Lettres indépendantes"))
        self.groupbox_word_list.setTitle(_translate("master", "Liste de mots :"))
        self.lineedit_word_list.setText(_translate("master", "liste_mots.txt"))
        self.groupbox_close.setTitle(_translate("master", "Définition de mot proche  :"))
        self.checkbox_c_startend2.setText(_translate("master", "Début ou fin sur 2 lettres"))
        self.checkbox_c_following3.setText(_translate("master", "1 x 3 Lettres successives"))
        self.checkbox_c_following2.setText(_translate("master", "1 x 2 Lettres successives"))
        self.checkbox_c_indep3.setText(_translate("master", "3 x 1 Lettres indépendantes"))
        self.checkbox_c_indep2.setText(_translate("master", "2 x 1 Lettres indépendantes"))
        self.pushbutton_generate.setText(_translate("master", "Générer"))
        self.pushbutton_default_settings.setText(_translate("master", "Par défaut"))
        self.pushbutton_help.setText(_translate("master", "Aide"))
        self.pushbutton_quit.setText(_translate("master", "Quitter"))
        self.groupbox_state_info.setTitle(_translate("master", "État :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    master = QtWidgets.QDialog()
    ui = Ui_master()
    ui.setupUi(master)
    master.show()
    sys.exit(app.exec_())

